"""Add category column to food and preparation tables

Revision ID: 9e4f9a936072
Revises:
Create Date: 2025-07-20 20:29:27.960379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4f9a936072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('preparation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preparation', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
