"""Add user, combination, and user_favorite tables

Revision ID: ff06292baa2f
Revises: 9e4f9a936072
Create Date: 2025-07-20 20:44:35.487800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff06292baa2f'
down_revision = '9e4f9a936072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item1', sa.String(length=100), nullable=False),
    sa.Column('item2', sa.String(length=100), nullable=False),
    sa.Column('item3', sa.String(length=100), nullable=False),
    sa.Column('item4', sa.String(length=100), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['combination_id'], ['combination.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite')
    op.drop_table('user')
    op.drop_table('combination')
    # ### end Alembic commands ###
